---
dockitems_remove:
- Launchpad
- Safari
- Messages
- Mail
- Maps
- Photos
- FaceTime
- Calendar
- Contacts
- Notes
- TV
- Podcasts
- 'App Store'
- Freeform
- Music
- Keynote
- Numbers
- Pages
- System Settings

dockitems_persist:
- name: "Canary Mail"
  path: "/Applications/Canary Mail.app/"
  pos: 1
- name: "Reminders"
  path: "/Applications/Reminders.app/"
  pos: 2
- name: "Brave Browser"
  path: "/Applications/Brave Browser.app/"
  pos: 4
- name: "Visual Studio Code"
  path: "/Applications/Visual Studio Code.app/"
  pos: 5
- name: "1Password"
  path: "/Applications/1Password.app/"
  pos: 7
