# Brewfile

# brew "ansible-lint"
# brew "ffmpeg"
# brew "node"
# brew "nvm"
# brew "pnpm"
# brew "python"
# brew "ripgrep"
# brew "wget"
# brew "yamllint"
# brew "yarn"
# brew "youtube-dl"
brew "ansible"
brew "antidote"
brew "dockutil"
brew "eza"
brew "fzf"
brew "git"
brew "go"
brew "mas"
brew "nvim"
brew "starship"
brew "stow"
brew "tmux"
brew "zoxide"


#############
### Taps  ###
#############

tap "homebrew/cask-fonts"

#############
### Casks ###
#############

# code
cask "visual-studio-code"

# terminal
cask "kitty"

# browser
cask "brave-browser"
# cask "google-chrome"
# cask "firefox"

# password manager
cask "1password"
cask "keeweb"

# video
# cask "vlc"

# clipboard manager
cask "maccy"

# calendar
cask "fantastical"

# utility
# cask "hiddenbar"
cask "appcleaner"

# docker
cask "docker"

# window
cask "alt-tab"
cask "rectangle"

# vpn
# cask "mullvadvpn"

# bookmark
# cask "raindropio"

# file
# cask "dropzone"
# cask "cryptomator"

# pdf
cask "pdf-expert"

# torrent
# cask "transmission"

# fonts
cask "font-monaspace"
cask "font-symbols-only-nerd-font"

# api
# cask "postman"

# notes
cask "obsidian"
