---
- hosts: localhost
  connection: local
  vars_files:
    - vault.yml

  pre_tasks:

  roles:
    - role: apps/homebrew
      tags:
        - homebrew
        - apps
    - role: apps/mas
      tags:
        - mas
        - apps
    - role: apps/dock
      tags:
        - dock
        - apps
    - role: git
      tags:
        - git
    - role: ssh
      tags:
        - ssh
