---
- hosts: localhost
  connection: local

  pre_tasks:

  roles:
    - role: apps/homebrew
      tags:
        - homebrew
        - apps
    - role: apps/mas
      tags:
        - mas
        - apps
    - role: apps/dock
      tags:
        - dock
        - apps
