- name: Apply dotfiles for {{ item }}
  vars:
    user_home: "{{ lookup('env', 'HOME') }}"
  environment:
    STOW_DIR: "{{ user_home }}/dotfiles"
  shell: |
    stow {{ item | basename }}
  changed_when: false