---
mas_uninstalled_apps:
  - { id: 408981434, name: "iMovie" }
  - { id: 409183694, name: "Keynote" }
  - { id: 409201541, name: "Pages" }
  - { id: 409203825, name: "Numbers" }
  - { id: 682658836, name: "GarageBand" }

mas_installed_apps:
  - { id: 1236045954, name: "Canary Mail" }

mas_upgrade_all_apps: false