- name: Ensure .ssh directory exists
  file:
    path: ~/.ssh
    state: directory
    mode: '0700'
    
- name: Copy SSH key to .ssh folder
  ansible.builtin.copy:
    content: "{{ ssh_private_key }}"
    dest: ~/.ssh/id_ed25519
    mode: '0600'

- name: Generate ssh config
  ansible.builtin.template:
    src: templates/config.j2
    dest: ~/.ssh/config
    mode: '0600'